import "./globals.css";
import localFont from "next/font/local";
const amazonEmber = localFont({
  src: "./assets/fonts/AmazonEmber_Rg.ttf",
});
export const metadata = {
  title: "Zamazon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={amazonEmber.className}>{children}</body>
    </html>
  );
}
